function Hd = BandPass2HzSamp250Hz
%BANDPASS2HZSAMP250HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 14-Apr-2025 05:21:06

% Equiripple Bandpass filter designed using the FIRPM function.
% order = 633
% All frequency values are in Hz.
Fs = 250;  % Sampling Frequency

Fstop1 = 1;               % First Stopband Frequency
Fpass1 = 2;               % First Passband Frequency
Fpass2 = 100;             % Second Passband Frequency
Fstop2 = 101;             % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
