function Hd = notchFilter50Hz
%NOTCHFILTER50HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 24-Feb-2025 05:00:14

% Equiripple Bandstop filter designed using the FIRPM function.
% Order: 786
% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Fpass1 = 46;              % First Passband Frequency
Fstop1 = 49.5;            % First Stopband Frequency
Fstop2 = 50.5;            % Second Stopband Frequency
Fpass2 = 54;              % Second Passband Frequency
Dpass1 = 0.057501127785;  % First Passband Ripple
Dstop  = 0.0001;          % Stopband Attenuation
Dpass2 = 0.057501127785;  % Second Passband Ripple
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
